CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'sab'@'%' IDENTIFIED BY 'sab12345';
GRANT ALL PRIVILEGES ON wordpress.* TO 'sab'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root12345';